   clear;

   a=figure('Position',[50 275 400 300],'color','b')
   b=figure('Position',[500 175 500 500],'color','k')

   h1 = uicontrol(a,...
  'Units','characters',...
  'BackgroundColor','w',...
  'ListboxTop',0,...
  'Position',[10 10 60 10],...
  'String','ENSTA IN103 VIEW MOL');

   h2 = uicontrol(a,...
  'Units','characters',...
  'BackgroundColor',[1 1 1],...
  'ListboxTop',0,...
  'Position',[10 4 14 2],...
  'String','dna.xyz',...
  'Style','edit');

   h3 = uicontrol(a,...
  'Units','characters',...
  'Callback','close(b); prinmol;',...
  'ListboxTop',0,...
   'Position',[25 4 10 2],...
   'String','Load',...
   'Tag','Load');

   h4 = uicontrol(a,...
  'Units','characters',...
  'Callback','close(a); close(b);',...
  'ListboxTop',0,...
   'Position',[40 4 10 2],...
   'String','Close',...
   'Tag','Close');


